language: node_js
node_js: "10"
branches:
  only:
  - master
cache:
  directories:
    - node_modules
addons:
  apt:
    packages:
      - mysql-server-5.6
before_install:
  - mysql -e 'CREATE DATABASE project2_test;'
